version: '3'

services:
  nginx:
    image: yosmy/nginx
    container_name: muchacuba_api_nginx
    networks:
      - proxy
      - muchacuba
    working_dir: /var/www
    environment:
      - VIRTUAL_HOST=api.muchacuba.com
      - LETSENCRYPT_HOST=api.muchacuba.com
      - LETSENCRYPT_EMAIL=contact@muchacuba.com
  php:
    image: yosmy/php
    container_name: muchacuba_api_php
    networks:
      - muchacuba
    working_dir: /var/www
  mongo:
    image: yosmy/mongo
    container_name: muchacuba_api_mongo
    volumes:
      - ../var/db:/data/db
    networks:
      - muchacuba

networks:
  proxy:
    external: true
  muchacuba:
    external: true