version: '2'
services:
  node:
    image: node:9.2.0-alpine
    container_name: muchacuba_node
    ports:
      - 3000:3000
    links:
      - nginx
    volumes:
      - ../app:/app
    working_dir: /app/
    environment:
      - HTTPS=true
    command: "npm start"
  nginx:
    volumes:
      - ./nginx/default_dev.conf:/etc/nginx/conf.d/default.conf
      - ../app/build:/var/www
  php:
    volumes:
      - ./php/php_dev.ini:/usr/local/etc/php/php.ini
      - ../api:/var/www/
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=172.18.0.1"
  mongo:
    ports:
      - 27017:27017