version: '2'
services:
  bind:
    image: sameersbn/bind:9.9.5-20161106
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "10000:10000/tcp"
    volumes:
      - ./bind:/data
    restart: always