version: '2'
services:
  nginx:
    volumes:
      - ./nginx/default_prod.conf:/etc/nginx/conf.d/default.conf
      - ../app/build:/var/www
  php:
    volumes:
      - ./php/php_prod.ini:/usr/local/etc/php/php.ini
      - ../api:/var/www/
  cron:
    image: cubalider/php
    container_name: muchacuba_cron
    volumes:
      - ../api:/var/www
      - ./php/php_prod.ini:/usr/local/etc/php/php.ini
      - ./cron:/root/cron
    links:
      - mongo
    working_dir: /var/www
    entrypoint: /root/cron/entrypoint.sh
    environment:
      PHP_IDE_CONFIG: "serverName=docker"
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_host=172.18.0.1"
    restart: always