mongo_host: 'mongo'
mongo_port: '27017'
mongo_db: 'dev_muchacuba'
google_browser_api: 'AIzaSyApFrRpHVKRK1pvBchd0rcC_ycUa0H-5AU-5AU'
google_server_api: 'AIzaSyAorAcCtSRoQ72J7jCRswxpu0hAbM4Gxyk'
algolia_application: 'ZTNV94A2IT'
algolia_api: 'bd26c4a2dc8f86482c0b924d3256e909'
algolia_mule_offer_index: 'dev_mule_offers'
proxy: null
fb_app_id: '837622639692718'
fb_app_secret: 'd544fc93cad437addc2930a8f09d834c'
fb_default_graph_version: 'v2.2'
firebase_web_api_key: ''
firebase_project_id: 'cubalider-muchacuba'
# Internauta
mysql_host: ''
mysql_db: ''
mysql_user: ''
mysql_pass: ''
log_dir: ''
mailgun_api_key: ''
google_key: ''
google_cx_images: ''
google_cx_revolico: ''
google_cx_lyrics: ''
google_cx_horoscope: ''
algolia_user_index: 'dev_users'